settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: /home/yukpiz/go/1.12.4/src/github.com/yukpiz/go-translator-example
  path: /home/yukpiz/go/1.12.4/src/github.com/yukpiz/go-translator-example
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
